### ISSUE TITLE
@scroll

### ISSUE THREAD

**Issue by tvld** [wonderful-panda/vue-resizesensor#1]
Great helper:)

I would need just the same, but instead of the size I would need to fire on `@scroll` and get  `this.left`. I will use it to see in an element is scrolled beyond the right border.
Is this possible?

**Comment by wonderful-panda** [comment]
Sorry, I don't quite understand what you mean.

Would you give me a reason why you want to attach `@scroll` to `resize-sensor` instead of outer element(`#container` of below example) ?

``` html
<div id="container" style="display: relative;">
  <resize-sensor @resized="onResize"></resize-sensor>
  <some-content></some-content>
</div>
```

**Comment by tvld** [comment]
Thanks. I solved the scan of scrolling,  directly. Now I can for example show an arrow to indicate when a user scrolled a div out of the window:

``` js
methods: {
      setPos: function () {
        // find position of the tabs and see if it is scrolled out of window
        let e = document.getElementById("tabbox")
        this.isOffLeft = e.getBoundingClientRect().left < 0
        this.isOffRight = e.getBoundingClientRect().right > (window.innerWidth - 20)
      }
}
```
